name: Deploy Azure Function App

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js (for Azure Functions Core Tools)
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Azure Functions Core Tools
        run: npm install -g azure-functions-core-tools@4 --unsafe-perm

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: "IOTFXNAPPALEKHABECKER"
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'
